[workspace]
resolver = "2"

members = [
    "minigrep",
    "closure",
    "temp",
    "trait/deref",
    "smart_pointer/refcell",
    "gui",
    "state_pattern",
    "macro/hello_macro",
    "web",
]
